---
pipeline: BBBC043
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: false
    file: <metadata file name>
    merge_column: <Column to merge on>
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
  min_cells: 1
normalize_negcon:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
  min_cells: 1
feature_select:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
  min_cells: 1
feature_select_negcon:
  perform: false
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
  min_cells: 1
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: BBBC043
plates:
  - name: 52649
    process: true
  - name: 52651
    process: true
  - name: 52652
    process: true
  - name: 52653
    process: true
  - name: 52654
    process: true
  - name: 52657
    process: true
  - name: 52662
    process: true
  - name: 52663
    process: true
  - name: 52664
    process: true
  - name: 52665
    process: true
  - name: 52666
    process: true
  - name: 52671
    process: true
  - name: 52672
    process: true
  - name: 52673
    process: true
  - name: 52674
    process: true
  - name: 52675
    process: true
process: true
